### ISSUE TITLE
RE3 multi bug

### ISSUE THREAD

**Issue by otamega72** [IntelOrca/biorand#298]
### Version

3.0.0

### Seed

R730-A1YR-ZTRQHTEZ3Z900N8K8K40ZZZZZZZZZZZZZZZ

### Scenario

RE 3 (Jill)

### What happened?

* [ ] 1)  Connected 204:0 to 40A:0 -> crash
* [x] 2) 208 crash when zombies burst windows
* [ ] 3) 11b crash when using tv remote control
* [x] 4) 20c cable car , crash when Mikhail tried to kill Nemesis.
* [x] 5) Connected 201:0 to 205:2 (#312)
205 is restaurant front door  , 201 open door to  205 , but 205 cannot back to 201 , it actually back to restaurant. 
* [x] 6) hospital : after you opened the safe in ward 402 ,  if you go back to hospital again , it will trigger the bomb and there is no way to stop the clock count down (game over) (#313)
* [x] 7)  Connected 30A:1 to 20B:0   -> crash , but 203 -> 20B no problem . (#337)
* [x] 8) npc missing head : (#352)
![Capture](https://user-images.githubusercontent.com/120957601/225290112-47cc6dee-67e0-422c-8ca4-79a6769b18c3.JPG)

**Comment by IntelOrca** [comment]
I am having trouble reproducing 1, 3, 4, and 7. Are you able to provide some saved games that trigger the crash when entering those rooms?

**Comment by otamega72** [comment]
save :
01 :  Connected 204:0 to 40A:0 ( lift ) -> crash 
02 :  11b crash when using tv remote control
03 :  npc missing head in cable car
04 :  20c cable car , crash when Mikhail tried to kill Nemesis.
05 :   Connected 30A:1 to 20B:0 -> crash (Maybe trigger Mikhail's shooting zombies cause the crash )
06 :  203:1 -> 20B:2 , no crash , but open door 20B:0  and turn back , crash.
[re3.bug.zip](https://github.com/IntelOrca/biorand/files/11009995/re3.bug.zip)

**Comment by IntelOrca** [comment]
I think most of the issues are fixed now. A new issue can be created if any happen still with a later version.
